# Generated by Django 5.2.5 on 2025-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='image_url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='partner',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
