# Generated by Django 5.2.5 on 2025-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_url_partner_link_partner_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='info_icons/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.CharField(blank=True),
        ),
    ]
