# Generated by Django 5.2.5 on 2025-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_infoblock_alter_partner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
