# Generated by Django 5.2.5 on 2025-08-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='logos',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
