# Generated by Django 5.2.5 on 2025-08-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_logos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='insights/')),
                ('category', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True)),
            ],
        ),
    ]
