# Generated by Django 5.2.5 on 2025-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_insights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insights',
            name='link',
        ),
        migrations.AddField(
            model_name='insights',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='insights_file/'),
        ),
    ]
