# Generated by Django 5.2.5 on 2025-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('body_is_html', models.BooleanField(default=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='about/')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
