# Generated by Django 5.2.5 on 2025-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAGE', 'Page Meta'), ('ITEM', 'Service Item')], db_index=True, default='ITEM', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('body', models.TextField(blank=True)),
                ('body_is_html', models.BooleanField(default=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('featured', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
